# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_ADMIN:       [ROLE_EDITOR]
        ROLE_EDITOR:      [ROLE_USER]

    providers:
        fos_userbundle:
            id: uecode.api_key.provider.user_provider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        auth_token:                                   # Everyone can access the access token URL.
            pattern: ^/user/login
            security: false

        api:
            anonymous: ~
            api_key: true
            stateless: true                            # Do no set session cookies
            context: main
